{
 "title": "Application Load Balancer Ingress",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Prometheus", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits,cluster)"
    }
   },
   {
    "name": "load_balancer",
    "label": "load_balancer",
    "query": {
     "query": "label_values(aws_applicationelb_active_connection_count_average{cluster=\"$cluster\"},load_balancer)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(aws_applicationelb_request_count_per_target_sum{cluster=\"$cluster\"},target_group)"
    }
   },
   {
    "name": "ingress",
    "label": "ingress",
    "query": {
     "query": "label_values(aws_applicationelb_target_response_time_average{cluster=\"$cluster\", load_balancer=\"$load_balancer\"},target_group)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Ingress Requests",
   "type": "timeseries",
   "description": "The total sum of all requests across the filtered target group(s).",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (load_balancer)(aws_applicationelb_request_count_sum{cluster=\"$cluster\",load_balancer=\"$load_balancer\",target_group=~\"$ingress\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum by(load_balancer) (deriv(aws_applicationelb_request_count_sum{cluster=\"$cluster\", load_balancer=\"$load_balancer\", target_group=~\"$ingress\"}[10m]))",
     "legendFormat": "Rate of change"
    }
   ]
  },
  {
   "title": "Requests Per Target ",
   "type": "timeseries",
   "description": "Request count per target in the target group. This value is derived from the total number of requests divided by the number of healthy targets in the target group.",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "sum by (load_balancer)(aws_applicationelb_request_count_per_target_sum{cluster=\"$cluster\",load_balancer=\"$load_balancer\",target_group=~\"$ingress\"})",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Response StatusCode Sum",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "sum by (load_balancer)(aws_applicationelb_httpcode_target_2_xx_count_sum{cluster=\"$cluster\",load_balancer=\"$load_balancer\",target_group=~\"$ingress\"})",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum by (load_balancer)(aws_applicationelb_httpcode_target_3_xx_count_sum{cluster=\"$cluster\",load_balancer=\"$load_balancer\",target_group=~\"$ingress\"})",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum by (load_balancer)(aws_applicationelb_httpcode_target_4_xx_count_sum{cluster=\"$cluster\",load_balancer=\"$load_balancer\",target_group=~\"$ingress\"})",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum by (load_balancer)(aws_applicationelb_httpcode_target_5_xx_count_sum{cluster=\"$cluster\",load_balancer=\"$load_balancer\",target_group=~\"$ingress\"})",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Response StatusCode Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(aws_applicationelb_httpcode_target_2_xx_count_sum{cluster=\"$cluster\",target_group=~\"$ingress\"}) / (\n    sum(aws_applicationelb_httpcode_target_2_xx_count_sum{cluster=\"$cluster\",target_group=~\"$ingress\"}) + sum(aws_applicationelb_httpcode_target_4_xx_count_sum{cluster=\"$cluster\",target_group=~\"$ingress\"} or vector(0))+ sum(aws_applicationelb_httpcode_target_3_xx_count_sum{cluster=\"$cluster\",target_group=~\"$ingress\"} or vector(0)) +  sum(aws_applicationelb_httpcode_target_5_xx_count_sum{cluster=\"$cluster\",target_group=~\"$ingress\"} or vector(0))\n) * 100",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(aws_applicationelb_httpcode_target_3_xx_count_sum{cluster=\"$cluster\",target_group=~\"$ingress\"}) / (\n    sum(aws_applicationelb_httpcode_target_2_xx_count_sum{cluster=\"$cluster\",target_group=~\"$ingress\"}) + sum(aws_applicationelb_httpcode_target_4_xx_count_sum{cluster=\"$cluster\",target_group=~\"$ingress\"} or vector(0))+ sum(aws_applicationelb_httpcode_target_3_xx_count_sum{cluster=\"$cluster\",target_group=~\"$ingress\"} or vector(0)) +  sum(aws_applicationelb_httpcode_target_5_xx_count_sum{cluster=\"$cluster\",target_group=~\"$ingress\"} or vector(0))\n) * 100",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(aws_applicationelb_httpcode_target_4_xx_count_sum{cluster=\"$cluster\",target_group=~\"$ingress\"}) / (\n    sum(aws_applicationelb_httpcode_target_2_xx_count_sum{cluster=\"$cluster\",target_group=~\"$ingress\"}) + sum(aws_applicationelb_httpcode_target_4_xx_count_sum{cluster=\"$cluster\",target_group=~\"$ingress\"} or vector(0))+ sum(aws_applicationelb_httpcode_target_3_xx_count_sum{cluster=\"$cluster\",target_group=~\"$ingress\"} or vector(0)) +  sum(aws_applicationelb_httpcode_target_5_xx_count_sum{cluster=\"$cluster\",target_group=~\"$ingress\"} or vector(0))\n) * 100",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(aws_applicationelb_httpcode_target_5_xx_count_sum{cluster=\"$cluster\",target_group=~\"$ingress\"}) / (\n    sum(aws_applicationelb_httpcode_target_2_xx_count_sum{cluster=\"$cluster\",target_group=~\"$ingress\"}) + sum(aws_applicationelb_httpcode_target_4_xx_count_sum{cluster=\"$cluster\",target_group=~\"$ingress\"} or vector(0))+ sum(aws_applicationelb_httpcode_target_3_xx_count_sum{cluster=\"$cluster\",target_group=~\"$ingress\"} or vector(0)) +  sum(aws_applicationelb_httpcode_target_5_xx_count_sum{cluster=\"$cluster\",target_group=~\"$ingress\"} or vector(0))\n) * 100",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Response StatusCode Ratio Avg",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(aws_applicationelb_httpcode_target_2_xx_count_sum{cluster=\"$cluster\",target_group=~\"$ingress\"} or vector(0)) / (\n    sum(aws_applicationelb_httpcode_target_2_xx_count_sum{cluster=\"$cluster\",target_group=~\"$ingress\"}) + sum(aws_applicationelb_httpcode_target_4_xx_count_sum{cluster=\"$cluster\",target_group=~\"$ingress\"} or vector(0))+ sum(aws_applicationelb_httpcode_target_3_xx_count_sum{cluster=\"$cluster\",target_group=~\"$ingress\"} or vector(0)) +  sum(aws_applicationelb_httpcode_target_5_xx_count_sum{cluster=\"$cluster\",target_group=~\"$ingress\"} or vector(0))\n) * 100",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(aws_applicationelb_httpcode_target_3_xx_count_sum{cluster=\"$cluster\",target_group=~\"$ingress\"} or vector(0)) / (\n    sum(aws_applicationelb_httpcode_target_2_xx_count_sum{cluster=\"$cluster\",target_group=~\"$ingress\"}) + sum(aws_applicationelb_httpcode_target_4_xx_count_sum{cluster=\"$cluster\",target_group=~\"$ingress\"} or vector(0))+ sum(aws_applicationelb_httpcode_target_3_xx_count_sum{cluster=\"$cluster\",target_group=~\"$ingress\"} or vector(0)) +  sum(aws_applicationelb_httpcode_target_5_xx_count_sum{cluster=\"$cluster\",target_group=~\"$ingress\"} or vector(0))\n) * 100",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(aws_applicationelb_httpcode_target_4_xx_count_sum{cluster=\"$cluster\",target_group=~\"$ingress\"} or vector(0)) / (\n    sum(aws_applicationelb_httpcode_target_2_xx_count_sum{cluster=\"$cluster\",target_group=~\"$ingress\"}) + sum(aws_applicationelb_httpcode_target_4_xx_count_sum{cluster=\"$cluster\",target_group=~\"$ingress\"} or vector(0))+ sum(aws_applicationelb_httpcode_target_3_xx_count_sum{cluster=\"$cluster\",target_group=~\"$ingress\"} or vector(0)) +  sum(aws_applicationelb_httpcode_target_5_xx_count_sum{cluster=\"$cluster\",target_group=~\"$ingress\"} or vector(0))\n) * 100",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(aws_applicationelb_httpcode_target_5_xx_count_sum{cluster=\"$cluster\",target_group=~\"$ingress\"} or vector(0)) / (\n    sum(aws_applicationelb_httpcode_target_2_xx_count_sum{cluster=\"$cluster\",target_group=~\"$ingress\"} or vector(0)) + sum(aws_applicationelb_httpcode_target_4_xx_count_sum{cluster=\"$cluster\",target_group=~\"$ingress\"} or vector(0))+ sum(aws_applicationelb_httpcode_target_3_xx_count_sum{cluster=\"$cluster\",target_group=~\"$ingress\"} or vector(0)) +  sum(aws_applicationelb_httpcode_target_5_xx_count_sum{cluster=\"$cluster\",target_group=~\"$ingress\"} or vector(0))\n) * 100",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Response Time Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (load_balancer)(aws_applicationelb_target_response_time_p99_00{cluster=\"$cluster\",load_balancer=\"$load_balancer\",target_group=~\"$ingress\"})",
     "legendFormat": "p99"
    },
    {
     "expr": "avg by (load_balancer)(aws_applicationelb_target_response_time_p90_00{cluster=\"$cluster\",load_balancer=\"$load_balancer\",target_group=~\"$ingress\"})",
     "legendFormat": "p90"
    },
    {
     "expr": "avg by (load_balancer)(aws_applicationelb_target_response_time_p95_00{cluster=\"$cluster\",load_balancer=\"$load_balancer\",target_group=~\"$ingress\"})",
     "legendFormat": "p95"
    },
    {
     "expr": "avg by (load_balancer)(aws_applicationelb_target_response_time_p70_00{cluster=\"$cluster\",load_balancer=\"$load_balancer\",target_group=~\"$ingress\"})",
     "legendFormat": "p70"
    },
    {
     "expr": "avg by (load_balancer)(aws_applicationelb_target_response_time_p50_00{cluster=\"$cluster\",load_balancer=\"$load_balancer\",target_group=~\"$ingress\"})",
     "legendFormat": "p50"
    },
    {
     "expr": "avg by (load_balancer)(aws_applicationelb_target_response_time_p20_00{cluster=\"$cluster\",load_balancer=\"$load_balancer\",target_group=~\"$ingress\"})",
     "legendFormat": "p20"
    }
   ]
  },
  {
   "title": "Response Percentile Latency Avg",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (load_balancer) (aws_applicationelb_target_response_time_p99_00{cluster=\"$cluster\",load_balancer=\"$load_balancer\",target_group=\"$ingress\"})",
     "legendFormat": "p99"
    },
    {
     "expr": "avg by (load_balancer)(aws_applicationelb_target_response_time_p95_00{cluster=\"$cluster\",load_balancer=\"$load_balancer\",target_group=\"$ingress\"})",
     "legendFormat": "p95"
    },
    {
     "expr": "avg by (load_balancer)(aws_applicationelb_target_response_time_p95_00{cluster=\"$cluster\",load_balancer=\"$load_balancer\",target_group=\"$ingress\"})",
     "legendFormat": "p90"
    },
    {
     "expr": "avg by (load_balancer)(aws_applicationelb_target_response_time_p50_00{cluster=\"$cluster\",load_balancer=\"$load_balancer\",target_group=\"$ingress\"})",
     "legendFormat": "p50"
    },
    {
     "expr": "avg by (load_balancer)(aws_applicationelb_target_response_time_p20_00{cluster=\"$cluster\",load_balancer=\"$load_balancer\",target_group=\"$ingress\"})",
     "legendFormat": "p20"
    }
   ]
  },
  {
   "title": "Ingress Connection Error Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum by (load_balancer) (aws_applicationelb_target_connection_error_count_sum{cluster=\"$cluster\",load_balancer=\"$load_balancer\",target_group=~\"$ingress\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LoadBalancer Connection Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum by (load_balancer)(aws_applicationelb_new_connection_count_sum{cluster=\"$cluster\",load_balancer=\"$load_balancer\"})",
     "legendFormat": "new_connections"
    },
    {
     "expr": "sum by (load_balancer)(aws_applicationelb_active_connection_count_sum{cluster=\"$cluster\",load_balancer=\"$load_balancer\"})",
     "legendFormat": "active_connections"
    }
   ]
  }
 ]
}